image: soseth/debian-ci-base:stretch

build:
  stage: build
  script:
    - dpkg-buildpackage -b -us -uc
    - mv ../*.deb . # GitLab can't copy from the parent directory...
  artifacts:
    name: packets
    expire_in: 3 months
    paths:
      - '*.deb'
