---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8router
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "watch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8router
subjects:
- kind: User
  name: k8router
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: k8router
  apiGroup: rbac.authorization.k8s.io
