---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8router
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - watch
      - list
      - get
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs:
      - watch
      - list
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8router
subjects:
  - kind: User
    name: k8router
    namespace: kube-system
