apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushd
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pushd
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "watch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pushd
subjects:
- kind: ServiceAccount
  name: pushd
  namespace: dev
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pushd
  apiGroup: rbac.authorization.k8s.io
